add I4A SSO via custom OAuth2 'Authorization Code Grant' flow (#1523)
* rename .runtimeconfig.json.dist -> .runtimeconfig.json.example
* move function exports closer to their requires
* sort function exports from index alphabetically
* npm install --save simple-oauth2
* add WIP skeleton of OAuth/SSO functions/related bits
* add firebase:emulate-functions-hosting script to package.json
* npm uninstall body-parser
* npm i node-fetch
* fix imports sort order in Login
* try to automatically login using customToken url param when present
* WIP: refactor backend functions to retrieve sso user details, lookup/create account, return customToken, etc
* WIP: refactor 'check meeting' code to process an array of meeting ids
* add postJson in functions/src/utils/fetch.js
* refactor I4A 'get user info' for recent changes in API
* add getJson in functions/src/utils/fetch.js
* fetch user's I4A ams_id from /oauth/userinfo
* rename I4A auth functions + url paths they are mapped to
* refactor getVenueId / checkIfValidVenueId from functions/venue to functions/src/utils/venue
* fix bug in checkIfValidVenueId when venueId isn't a string
* add /auth/connect/i4a + /auth/connect/i4a/handler routes to sparkle-ohbm
* add venueId param to connectI4AOAuth / connectI4AOAuthHandler + use it in redirects
* add auth.origin to function configuration + use it for redirects
* cleanup commented unsupported state cookie code + related
* npm i yup
* load auth config from firebase + related validations + refactor createOAuth2Client to consume this
* load I4A auth config from firebase + related validations + refactor functions to consume this
* explicitly disallow read/write to the authConfigs collection from the frontend
* Apply suggestions from code review
* ensure we check for code param properly
* refactor custom token handling into LoginWithCustomToken at /login/:venueId/:customToken
* fix createOAuth2Client to not be async
* add scope to authConfig
* add i4aMeetingIdsToCheck / i4aEventIdsToCheck to authConfig
* ensure we redirect back to /login/:venueId/:customToken
* throw error if we can't get i4aUserId
* fix TypeError: yup.lazy(...).default is not a function
* add i4aUserId / registeredMeetings / registeredEvents to user as custom claims
* rename Login__saml-login -> Login__quick-login-icon
* add the main boilerplate bits of 'quick login' for I4A OAuth SSO
* add title to SAML SSO login to show label onhover
* fix VenueEntrancePage import sort order
* comment out broken /login route + add @debt comment
* fix RoomsForm import sort order
* refactor Login to accept WithId<AnyVenue>
* fix signInWithI4AOAuth to append venueId to url
* remove insecure function config logging so as not to expose secrets in logs
* refactor check for existing logged in user to use useUser hook
* add assertValidVenueId in functions/src/utils/assert
* add isValidUrl in functions/src/utils/url
* add assertValidUrl in functions/src/utils/assert
* refactor functions/auth to use assertValidVenueId
* refactor backend functions to insecurely use returnOrigin from URL params instead of AUTH_ORIGIN
* add validReturnOrigins to authConfig + use it to securely validate that provided returnOrigin is trusted
* refactor checkIfValidVenueId to extract VENUE_ID_REGEX + create VenueIdSchema
* add firebase:emulate-functions-hosting:debug script to package.json
* add @debt comment to checkPassword backend function
* add functions/src/types/venue that I forgot to commit earlier
* add getCustomAuthConfig backend function + fetchCustomAuthConfig + use this in Login component
* include venueId in bugsnag context